version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: lblod/frontend-openproceshuis:1.2.0
    environment:
      EMBER_OAUTH_API_REDIRECT_URL: "https://openproceshuis.lblod.info/authorization/callback"
      EMBER_OAUTH_API_KEY: "aaf8877c-0975-4003-8db8-a9986355b80b"
      EMBER_OAUTH_API_BASE_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/auth"
      EMBER_OAUTH_API_LOGOUT_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/logout"
      EMBER_OAUTH_API_SCOPE: "openid rrn profile vo abb_openproceshuis"
      EMBER_OAUTH_SWITCH_URL: "https://openproceshuis.lblod.info/switch-login"
      EMBER_ANALYTICS_APP_DOMAIN: "openproceshuis.lblod.info" # Prod: openproceshuis.vlaanderen.be
      EMBER_ANALYTICS_API_HOST: "https://plausible.lblod.info"

    volumes:
      - ./config/frontend/add-x-frame-options-header.conf:/config/add-x-frame-options.conf
    labels:
      - "logging=true"
    logging: *default-logging
    restart: always
  identifier:
    image: semtech/mu-identifier:1.10.1
    labels:
      - "logging=true"
    logging: *default-logging
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"},{"variables":[],"name":"clean"}]'
    links:
      - dispatcher:dispatcher
    restart: always
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    logging: *default-logging
    labels:
      - "logging=true"
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    restart: always
  database:
    logging: *default-logging
    labels:
      - "logging=true"
    image: semtech/sparql-parser:0.0.13
    volumes:
      - ./config/authorization:/config
      - ./data/authorization:/data
    restart: always
  virtuoso:
    logging: *default-logging
    labels:
      - "logging=true"
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
  migrations:
    logging: *default-logging
    labels:
      - "logging=true"
    image: semtech/mu-migrations-service:0.9.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
  resource:
    logging: *default-logging
    labels:
      - "logging=true"
    image: semtech/mu-cl-resources:feature-unions-for-optional-deletes
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    restart: always
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier:0.2.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:feature-validate-readable-metadata
    labels:
      - "logging=true"
    logging: *default-logging
    links:
      - database:database
    volumes:
      - ./data/files:/share
    environment:
      VALIDATE_READABLE_METADATA: "true"
    restart: always
  bpmn:
    logging: *default-logging
    labels:
      - "logging=true"
    image: lblod/openproceshuis-bpmn-service:2.1.0
    volumes:
      - ./config/bpmn:/config
      - ./data/files:/share
    restart: always
  visio:
    logging: *default-logging
    labels:
      - "logging=true"
    image: lblod/openproceshuis-visio-service:0.0.1
    volumes:
      - ./data/files:/share
    restart: always
  accountdetail:
    image: lblod/account-detail-service:0.1.0
    labels:
      - "logging=true"
    links:
      - database:database
    restart: always
    logging: *default-logging

  ################################################################################
  # MU SEARCH
  ################################################################################
  search:
    image: semtech/mu-search:0.10.0-beta.5
    links:
      - database:database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
    volumes:
      - ./config/search/prd:/config
  elasticsearch:
    labels:
      - "logging=true"
    logging: *default-logging
    image: semtech/mu-search-elastic-backend:1.1.0
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always

  ################################################################################
  # OP PUBLIC CONSUMER
  ################################################################################
  op-public-consumer:
    image: lblod/delta-consumer:0.1.0
    environment:
      DCR_SERVICE_NAME: "op-public-consumer"
      DCR_SYNC_BASE_URL: "https://organisaties.abb.lblod.info" # replace with link to OP API
      DCR_SYNC_FILES_PATH: "/sync/public/files"
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/PublicCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/op-public"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/deltaSync/op-public"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/op-public-consumer"
      DCR_DISABLE_INITIAL_SYNC: "true"
      DCR_KEEP_DELTA_FILES: "true"
      DCR_DELTA_JOBS_RETENTION_PERIOD: "30"
      DCR_ENABLE_TRIPLE_REMAPPING: "true"
      DCR_LANDING_ZONE_GRAPH: "http://mu.semte.ch/graphs/op/landing"
      DCR_REMAPPING_GRAPH: "http://mu.semte.ch/graphs/public"
      DCR_BATCH_SIZE: 1000
      SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES: "404,500,503"
      SUDO_QUERY_RETRY: "true"
    volumes:
      - ./config/op-consumer/mapping:/config/mapping
      - ./data/consumer-files/op-public:/consumer-files/
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging

  ################################################################################
  # ACM/IDM
  ################################################################################
  login:
    image: lblod/acmidm-login-service:0.9.2
    environment:
      MU_APPLICATION_AUTH_USERID_CLAIM: "vo_id"
      MU_APPLICATION_AUTH_ROLE_CLAIM: "abb_openproceshuis_rol_3d"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "aaf8877c-0975-4003-8db8-a9986355b80b"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://openproceshuis.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "secret"
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  impersonation:
    image: lblod/impersonation-service

  ################################################################################
  # IPDC PROXY
  ################################################################################
  ipdc-proxy:
    image: lblod/api-proxy-service:1.0.2
    links:
      - virtuoso:database
    environment:
      API_URL: "https://api.ipdc.tni-vlaanderen.be"
      API_KEY: "secret"
      REQUIRED_ROLES: ""
      ALLOWED_ORIGIN: "*"
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging

  ################################################################################
  # REPORTING
  ################################################################################
  report-generation:
    image: lblod/loket-report-generation-service:0.8.2
    environment:
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/reports"
      ONLY_KEEP_LATEST_REPORT: "true"
    links:
      - virtuoso:database
    volumes:
      - ./data/files:/share
      - ./config/reports:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
